trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Stage1
  jobs:
  - job: "Stage1Job1"
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
  - job: "Stage1Job2"
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
- stage: Stage2
  dependsOn: Stage1
  jobs:
  - job: Stage2Job1
    pool: server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
